// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TimeTrackingServer.Models;

namespace TimeTrackingServer.Migrations
{
    [DbContext(typeof(TimeTrackingDBContext))]
    [Migration("20170914181449_new22222")]
    partial class new22222
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeTrackingServer.Models.Costumer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("StreetAddress");

                    b.HasKey("Id");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("TimeTrackingServer.Models.Item", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<string>("description");

                    b.Property<float>("hours");

                    b.Property<long>("projectId");

                    b.Property<long>("userId");

                    b.Property<string>("workingPlace");

                    b.HasKey("id");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TimeTrackingServer.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CostumerId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CostumerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimeTrackingServer.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TimeTrackingServer.Models.Item", b =>
                {
                    b.HasOne("TimeTrackingServer.Models.Project", "project")
                        .WithMany()
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TimeTrackingServer.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TimeTrackingServer.Models.Project", b =>
                {
                    b.HasOne("TimeTrackingServer.Models.Costumer", "Costumer")
                        .WithMany()
                        .HasForeignKey("CostumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
